services:
  - type: web
    name: webapp5bykhagendra
    env: docker
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/WebApp5ByKhagendra.dll
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000 